version: '2.2'
services:
  api:
    build: .
    ports: 
      - "3002:3002"
    container_name: novel_api
    networks:
      - server_network
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - server_network
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links: 
      - db:db
    ports:
      - 8080:80
    environment:
      UPLOAD_LIMIT: 10000000000
    networks:
      - server_network

networks:
  server_network:
   

